# Generated by Django 4.0.5 on 2022-06-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cat', models.CharField(max_length=100)),
                ('descricao_cat', models.TextField()),
                ('video_cat', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('qtd_vizu', models.IntegerField()),
                ('video', models.URLField()),
                ('imagem', models.URLField()),
            ],
        ),
    ]
